In [26]:
import numpy as np
from scipy import ndimage, signal

rng = np.random.default_rng()
arr = np.arange(30, dtype=float)
rng.shuffle(arr)
data = arr.reshape(5, 6)
print(data)


kernel = np.array([[0.5, 1.0, 0.5], [0.5, 1.0, 0.5]], dtype=float)

# Spatial convolution
x = ndimage.convolve(data, kernel, mode="constant")  # ~200 ms
# FFT-based convolution
y = signal.fftconvolve(data, kernel, mode="valid")  # ~50 ms

[[17.  4. 18.  7. 10. 23.]
 [22.  1. 25. 12.  3. 20.]
 [26.  8.  6. 19. 16. 13.]
 [29. 21. 15. 14.  0. 24.]
 [11. 27.  5.  2.  9. 28.]]


In [27]:
print(x)

[[41.5 46.  55.  47.  44.  49.5]
 [52.5 48.5 51.  56.  51.  42.5]
 [69.5 67.  52.  51.5 51.  45. ]
 [64.  78.  52.  30.5 43.  56.5]
 [24.5 35.  19.5  9.  24.  32.5]]


In [28]:
print(y)

[[46.  55.  47.  44. ]
 [48.5 51.  56.  51. ]
 [67.  52.  51.5 51. ]
 [78.  52.  30.5 43. ]]


In [3]:
def f(a, b, *args, **kwargs):
    return a + b + args[0] + args[1]


f(1, 2, 3, 4)

10