In [2]:
import numpy as np

In [7]:
ndim = 2
rhs = np.arange(30).reshape((6, 5))
igs = [2, 2]
factor = 100
wall_idx = np.empty((ndim), dtype=object)
for dim in range(ndim):
    wall_idx[dim] = slice(igs[dim], -igs[dim])
print(rhs)
for dim in range(ndim):
    if True:
        for direction in [-1, 1]:
            wall_idx[dim] = (igs[dim] - 1) * direction
            if direction == -1:
                wall_idx[dim] -= 1
            wall_idx_tuple = tuple(wall_idx)
            rhs[wall_idx_tuple] *= factor
            print(wall_idx_tuple)

print(rhs)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
(-2, slice(2, -2, None))
(1, slice(2, -2, None))
(1, -2)
(1, 1)
[[   0    1    2    3    4]
 [   5  600  700  800    9]
 [  10   11   12   13   14]
 [  15   16   17   18   19]
 [  20   21 2200   23   24]
 [  25   26   27   28   29]]


Numba 2D:  0.530577 s per run
Scipy 2D:  0.076421 s per run
Numpy 2D:  0.018389 s per run
2D: Maximum difference in grad_x numba: 1.1102230246251565e-16
2D: Maximum difference in grad_x numpy: 1.1102230246251565e-16

Benchmarking 3D implementations
Numba 3D:  1.708513 s per run
Scipy 3D:  1.813149 s per run
Numpy 3D:  0.564412 s per run
3D: Maximum difference in grad_x numba: 3.3306690738754696e-16
3D: Maximum difference in grad_x numpy: 3.3306690738754696e-16
